use serde::{Deserialize, Serialize};
use std::{collections::HashMap, sync::Mutex};
use tauri::State;

use crate::{
    audio_engine::AudioEngineMessaging,
    audio_node::{
        CreateEffectNodeRequest, EffectNode, EffectNodePayload, EffectNodeTypes, GainNode,
    },
};

/// This is a unique ID generated by the frontend that's saved to backend
/// and used as a primary key for associations (like a relational DB)
type TrackId = String;

/// A track that can be associated with `TrackClip` and `TrackEffect`
#[derive(Clone, Serialize, Deserialize)]
pub struct Track {
    pub name: TrackId,
    /// Index for corrresponding MixerTrack on RT thread
    pub pool_index: usize,
    pub muted: bool,
    pub gain: f32,
}

impl Track {
    pub fn new(name: TrackId, muted: bool, pool_index: usize) -> Self {
        Self {
            name,
            pool_index,
            muted,
            gain: 1.0,
        }
    }
}

/// Audio effect associated with a track.
pub struct TrackEffect {
    pub track_id: TrackId,
    pub effect: EffectNodeTypes,
}

impl TrackEffect {
    pub fn new(track_id: TrackId, effect: EffectNodeTypes) -> Self {
        Self { track_id, effect }
    }
}

/// A stack of audio effects on the designated track
pub type TrackEffects = HashMap<TrackId, TrackEffect>;

#[derive(Clone, Serialize, Deserialize)]
pub enum TrackClipType {
    Sample,
    Synthesizer,
}

/// A single "clip" on the track. This associates a `Track` with a `Clip`.
#[derive(Clone, Serialize, Deserialize)]
pub struct TrackClip {
    pub id: String,
    pub track_clip_type: TrackClipType,
    pub clip_id: String,
    pub start_time: f64,
    pub enabled: bool,
}

impl TrackClip {
    pub fn new(
        id: String,
        clip_id: String,
        start_time: f64,
        enabled: bool,
        track_clip_type: TrackClipType,
    ) -> Self {
        Self {
            id,
            clip_id,
            start_time,
            enabled,
            track_clip_type,
        }
    }
}

// We associate TrackClips with a Track ID (aka String)
type TrackClips = HashMap<TrackId, Vec<TrackClip>>;

#[derive(Clone, Serialize, Deserialize)]
pub enum ClipType {
    Sample,
    Midi,
}

/// Media that's been loaded for use in composition.
/// This associates to the appropriate clip type cache (e.g. sample vs MIDI)
#[derive(Clone, Serialize, Deserialize)]
pub struct Clip {
    pub name: String,
    pub duration: f64,
    // Clips can reference different types of audio data
    pub clip_type: ClipType,
    // This references the ID on the appropriate cache (e.g. sample cache)
    pub clip_id: String,
}

impl Clip {
    pub fn new(name: String, duration: f64, clip_type: ClipType, clip_id: String) -> Self {
        Self {
            name,
            duration,
            clip_type,
            clip_id,
        }
    }
}

/// The user's current composition (aka "timeline") of audio.
/// Consists of multiple `Track` that contain multiple `Clip`.
/// Each track can have a stack of FX (aka `TrackEffect`) applied.
/// The clips represent `MediaAsset` we need loaded and cached for use.
pub struct CompositionStore {
    // Start / end time of timeline
    pub range: (f64, f64),
    pub tracks: HashMap<String, Track>,
    pub track_clips: TrackClips,
    pub clips: HashMap<String, Clip>,
    pub track_effects: TrackEffects,
    pub play_midi_track: String,
}

impl CompositionStore {
    pub fn new() -> Self {
        let range = (0.0, 1.0);
        let tracks = HashMap::new();
        let track_clips = HashMap::new();
        let clips = HashMap::new();
        let track_effects = HashMap::new();

        Self {
            range,
            tracks,
            track_clips,
            clips,
            track_effects,
        }
    }

    /// Resets the store to its initial state by overwriting it with a new instance.
    pub fn reset(&mut self) {
        *self = Self::new();
    }
}

#[tauri::command()]
pub async fn reset_composition(
    composition_store: State<'_, Mutex<CompositionStore>>,
) -> Result<(), String> {
    let mut store = composition_store
        .lock()
        .map_err(|_| "Couldn't lock composition store")?;

    store.reset();

    Ok(())
}

#[tauri::command()]
pub async fn add_track(
    composition_store: State<'_, Mutex<CompositionStore>>,
    track_id: String,
    name: String,
) -> Result<bool, String> {
    let store_result = composition_store.lock();

    if let Ok(mut store) = store_result {
        let index = store.tracks.len();
        if index > 20 {
            return Err("Max 20 tracks".to_string());
        }

        let new_track = Track::new(name, false, index);
        store.tracks.insert(track_id.clone(), new_track);
        store.track_clips.insert(track_id, Vec::new());
        return Ok(true);
    }

    Err("Couldn't lock composition store".to_string())
}

#[tauri::command()]
pub async fn update_track_gain(
    messaging: State<'_, AudioEngineMessaging>,
    composition_store: State<'_, Mutex<CompositionStore>>,
    track_id: String,
    gain: f32,
) -> Result<bool, String> {
    let store_result = composition_store.lock();

    if let Ok(mut store) = store_result {
        if let Some(track) = store.tracks.get_mut(&track_id) {
            // Update value in Composition store ("Track")
            track.gain = gain;

            // Sync value to the audio backend ("MixerTrack")
            messaging.update_mixer_track_gain(track.pool_index, gain);

            return Ok(true);
        }
    }

    Err("Couldn't lock composition store".to_string())
}

#[tauri::command()]
pub async fn add_track_effect(
    composition_store: State<'_, Mutex<CompositionStore>>,
    track_id: String,
    effect_id: String,
    effect_data: EffectNodePayload,
) -> Result<bool, String> {
    let store_result = composition_store.lock();

    if let Ok(mut store) = store_result {
        let node;
        match effect_data {
            EffectNodePayload::Gain { gain } => node = EffectNodeTypes::Gain(GainNode::new(gain)),
        }

        let track_effect = TrackEffect::new(track_id, node);

        store.track_effects.insert(effect_id, track_effect);

        return Ok(true);
    }

    Err("Couldn't lock composition store".to_string())
}

#[tauri::command()]
pub async fn update_track_effect(
    composition_store: State<'_, Mutex<CompositionStore>>,
    effect_id: String,
    effect_data: EffectNodePayload,
) -> Result<bool, String> {
    let store_result = composition_store.lock();

    if let Ok(mut store) = store_result {
        // Find the track effect in store
        let effect_result = store.track_effects.get_mut(&effect_id);

        match effect_result {
            Some(track_effect) => {
                // Update the node based on data provided by user
                match effect_data {
                    EffectNodePayload::Gain { gain } => {
                        // Update the existing gain node
                        let EffectNodeTypes::Gain(ref mut gain_node) = track_effect.effect;
                        gain_node.set_gain(gain);
                    }
                }
            }
            None => todo!(),
        }

        return Ok(true);
    }

    Err("Couldn't lock composition store".to_string())
}

#[tauri::command()]
pub async fn add_track_clip(
    composition_store: State<'_, Mutex<CompositionStore>>,
    track_id: String,
    track_data: TrackClip,
) -> Result<bool, String> {
    let store_result = composition_store.lock();

    if let Ok(mut store) = store_result {
        store
            .track_clips
            .entry(track_id)
            .or_insert_with(Vec::new)
            .push(track_data);

        return Ok(true);
    }

    Err("Couldn't lock composition store".to_string())
}

/// Update track clip start time by provided time (in seconds)
#[tauri::command()]
pub async fn update_track_clip_time(
    composition_store: State<'_, Mutex<CompositionStore>>,
    track_id: String,
    id: String,
    time: f64,
) -> Result<bool, String> {
    let store_result = composition_store.lock();

    if let Ok(mut store) = store_result {
        if let Some(track_clips) = store.track_clips.get_mut(&track_id) {
            if let Some(current_clip) = track_clips
                .iter_mut()
                .find(|track_clip| &track_clip.id == &id)
            {
                current_clip.start_time = time;
                return Ok(true);
            }
        }
    }

    return Err("Couldn't update clip time".to_string());
}

#[tauri::command()]
pub async fn add_clip(
    composition_store: State<'_, Mutex<CompositionStore>>,
    clip_id: String,
    clip_data: Clip,
) -> Result<bool, String> {
    let store_result = composition_store.lock();

    if let Ok(mut store) = store_result {
        store.clips.insert(clip_id, clip_data);
        return Ok(true);
    }

    Err("Couldn't lock composition store".to_string())
}
